### PR TITLE
Offset random seed for setup and teardown

### LINKED ISSUE #22: Make random state different for test fixtures and the tests themselves
As discussed in #19, it's sometimes undesirable that we reset the random seed to the exact same value for fixtures and for tests - if both use the same data generation strategy (e.g. factory boy) they can end up generating the exact same objects which is a less useful test than the randomness they are trying to employ.

What we could do is use multiple random states based upon the seed we've been given (e.g. seed, seed + 1, seed +2) for test setup, test running, test teardown, etc. Or we could just advance the random generator with the same seed an arbitrary amount e.g. generate 100 random numbers before the test setup, but 0 random numbers before the test.

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #22.

### CODE REVIEW

**Comment by rouge8** [comment]
@adamchainz this works great for us!

**Comment by adamchainz** [comment]
Released on PyPI at 1.1.0 https://pypi.python.org/pypi/pytest-randomly

**Comment by rouge8** [comment]
Awesome, thanks again! Found another flaky test in our projects already. 😩

**Comment by kmantelpton** [comment]
Can this behavior be added as an option instead?

**Comment by adamchainz** [comment]
@kmantelpton please open a new issue and explain what problems it's causing you

**Pull request merged**
